version: '3.9'

services:
  application:
    container_name: 'application'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  database:
    image: mongo:4.4.1
    container_name: 'database'
    ports:
      - '27017:27017'
